In [1]:
import numpy as np
import os 
os.environ['TF_ENABLE_ONEDNN_OPTS']='0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf 
from tensorflow import keras

In [5]:
ALL_DATA_DIR = '/media/windows/'
training = ALL_DATA_DIR + 'training/'
validation = ALL_DATA_DIR + 'validation/'
scaled = ALL_DATA_DIR + 'scaled/'
scaled_wo_rotate = ALL_DATA_DIR + "scaled_wo_rotate/"

scaled_wo_rotate_training = scaled_wo_rotate + "training/"
scaled_wo_rotate_validation = scaled_wo_rotate + "validation/"

datFile = training + "shape_predictor_68_face_landmarks.dat"

In [6]:
batch_size = 32 
img_height = 224
img_width = 224 

In [7]:
validation_ds = tf.keras.utils.image_dataset_from_directory(scaled_wo_rotate_validation, labels = 'inferred', 
            label_mode = 'int', image_size=(img_height,img_width), batch_size=batch_size, seed=42).prefetch(1)

Found 50947 files belonging to 7 classes.


In [8]:
training_ds = tf.keras.utils.image_dataset_from_directory(scaled_wo_rotate_training, labels = 'inferred',
            label_mode = 'int', image_size=(img_height,img_width), batch_size=batch_size, seed=42).prefetch(1)

Found 399839 files belonging to 7 classes.


In [9]:
base_model = keras.applications.MobileNetV3Small(input_shape=(224,224,3), include_top = False, weights='imagenet')

In [10]:
avg = keras.layers.GlobalAveragePooling2D()(base_model.output)
output = keras.layers.Dense(7, activation='softmax')(avg)
model = keras.Model(inputs=base_model.input, outputs=output)

In [11]:
for layer in base_model.layers:
    layer.trainable = False

In [12]:
model.compile(optimizer="Adam",
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(training_ds, validation_data=validation_ds, epochs=3)

Epoch 1/3
12495/12495 [==============================] - 479s 38ms/step - loss: 1.4990 - accuracy: 0.4277 - val_loss: 1.4195 - val_accuracy: 0.4642
Epoch 2/3
12495/12495 [==============================] - 537s 43ms/step - loss: 1.4167 - accuracy: 0.4607 - val_loss: 1.4086 - val_accuracy: 0.4632
Epoch 3/3
12495/12495 [==============================] - 407s 33ms/step - loss: 1.4066 - accuracy: 0.4652 - val_loss: 1.3993 - val_accuracy: 0.4697


In [58]:
for layer in base_model.layers:
    layer.trainable = True

In [59]:
opt = keras.optimizers.Adam(learning_rate=1e-4)

In [60]:
es = keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)

In [61]:
cp = keras.callbacks.ModelCheckpoint('0821_model', save_best_only=True)

In [39]:
validation_s = tf.keras.utils.image_dataset_from_directory(scaled_wo_rotate_validation, labels = 'inferred', 
            label_mode = 'int', image_size=(img_height,img_width), batch_size=1, shuffle=False)
training_s = tf.keras.utils.image_dataset_from_directory(scaled_wo_rotate_training, labels = 'inferred',
            label_mode = 'int', image_size=(img_height,img_width), batch_size=1, shuffle=False)

Found 50947 files belonging to 7 classes.
Found 399839 files belonging to 7 classes.


In [62]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
history = model.fit(training_ds, validation_data=validation_ds, epochs=10, callbacks=[cp, es])

Epoch 1/10
12495/12495 [==============================] - ETA: 0s - loss: 0.9340 - accuracy: 0.6515

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 850s 68ms/step - loss: 0.9340 - accuracy: 0.6515 - val_loss: 0.7836 - val_accuracy: 0.7088
Epoch 2/10
12495/12495 [==============================] - ETA: 0s - loss: 0.7275 - accuracy: 0.7284

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 844s 68ms/step - loss: 0.7275 - accuracy: 0.7284 - val_loss: 0.7067 - val_accuracy: 0.7420
Epoch 3/10
12495/12495 [==============================] - ETA: 0s - loss: 0.6406 - accuracy: 0.7628

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 844s 68ms/step - loss: 0.6406 - accuracy: 0.7628 - val_loss: 0.6699 - val_accuracy: 0.7566
Epoch 4/10
12495/12495 [==============================] - ETA: 0s - loss: 0.5756 - accuracy: 0.7870

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 845s 68ms/step - loss: 0.5756 - accuracy: 0.7870 - val_loss: 0.6577 - val_accuracy: 0.7634
Epoch 5/10
12495/12495 [==============================] - ETA: 0s - loss: 0.5251 - accuracy: 0.8073

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 841s 67ms/step - loss: 0.5251 - accuracy: 0.8073 - val_loss: 0.6445 - val_accuracy: 0.7723
Epoch 6/10
12495/12495 [==============================] - ETA: 0s - loss: 0.4831 - accuracy: 0.8226

INFO:tensorflow:Assets written to: 0821_model/assets


INFO:tensorflow:Assets written to: 0821_model/assets


12495/12495 [==============================] - 842s 67ms/step - loss: 0.4831 - accuracy: 0.8226 - val_loss: 0.6378 - val_accuracy: 0.7751
Epoch 7/10
12495/12495 [==============================] - 829s 66ms/step - loss: 0.4460 - accuracy: 0.8363 - val_loss: 0.6816 - val_accuracy: 0.7653
Epoch 8/10
12495/12495 [==============================] - 829s 66ms/step - loss: 0.4136 - accuracy: 0.8486 - val_loss: 0.6565 - val_accuracy: 0.7775
Epoch 9/10
12495/12495 [==============================] - 833s 67ms/step - loss: 0.3859 - accuracy: 0.8585 - val_loss: 0.6694 - val_accuracy: 0.7743


In [64]:
validation_s.class_names

['validation_anger',
 'validation_disgust',
 'validation_fear',
 'validation_happiness',
 'validation_neutral',
 'validation_sadness',
 'validation_surprise']

In [71]:
B = []
C = []
D = []
for image, label in validation_s.take(5):
    A = model.predict(image, label)
    B.append(A.round(2))
    C.append(label)
    

1/1 [==============================] - 0s 24ms/step


In [72]:
B

[array([[2.7274448e-01, 3.7470538e-02, 1.8059179e-01, 4.3732810e-04,
         1.1666359e-02, 5.1117642e-03, 4.9197772e-01]], dtype=float32),
 array([[9.9924278e-01, 7.5254567e-05, 1.5620465e-04, 1.7920227e-06,
         1.1429091e-04, 3.8608481e-04, 2.3581419e-05]], dtype=float32),
 array([[9.3479854e-01, 1.6944256e-02, 3.6108498e-02, 5.0345826e-04,
         2.2689122e-05, 1.8735834e-03, 9.7489916e-03]], dtype=float32),
 array([[8.2547951e-01, 1.6870426e-02, 1.4382675e-01, 2.5117747e-06,
         5.4438069e-04, 5.7362777e-04, 1.2702723e-02]], dtype=float32),
 array([[9.7870752e-02, 1.0748791e-01, 9.7099744e-02, 1.1581975e-04,
         4.3229669e-05, 6.9410884e-01, 3.2737511e-03]], dtype=float32)]

In [73]:
model.save("0821_Model.h5")